version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: safiraweb
    command: sh -c "./start_server.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: safirapostgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
  
  volumes:
    postgres_data: