version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safiraweb
    command: sh -c "./start_server.sh"
    volumes:
      - .:/home/python_web_app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: safirapostgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: facturacion
      POSTGRES_USER: esteban_lobos
      POSTGRES_PASSWORD: 12345

volumes:
  postgres_data: