# Generated by Django 5.2.4 on 2025-07-31 14:43

import django.db.models.deletion
import mapbox_location_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=55)),
                ('nombre_fantasia', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'distribuidora',
                'verbose_name_plural': 'distribuidoras',
                'ordering': ('nombre_fantasia',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_region', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regiones',
                'ordering': ('nom_region',),
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tip_cli', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'tipo_cliente',
                'verbose_name_plural': 'tipo_clientes',
                'ordering': ('nom_tip_cli',),
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_comuna', models.CharField(max_length=60)),
                ('ubicacion', mapbox_location_field.models.LocationField(map_attrs={})),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta.region')),
            ],
            options={
                'verbose_name': 'comuna',
                'verbose_name_plural': 'comunas',
                'ordering': ('nom_comuna',),
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_person', models.CharField(max_length=50)),
                ('nom_emp', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta.comuna')),
                ('id_distrib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta.distribuidora')),
                ('id_tip_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta.tipocliente')),
            ],
            options={
                'verbose_name': 'formulario',
                'verbose_name_plural': 'formularios',
                'ordering': ('correo',),
            },
        ),
    ]
