# Generated by Django 5.2.4 on 2025-08-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('url_archivo', models.CharField(max_length=255)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'archivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_form', models.AutoField(primary_key=True, serialize=False)),
                ('nom_person', models.CharField(max_length=50)),
                ('nom_emp', models.CharField(max_length=100)),
                ('rut_emp', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=60)),
                ('telefono', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('direccion', models.TextField()),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('consum_elect', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('demanda_max', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('demanda_max_hp', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('numero_cliente', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'formulario',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='distribuidora',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipocliente',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
    ]
