# Generated by Django 5.2.4 on 2025-08-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_archivo_formulario_alter_comuna_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comuna',
            table='comuna',
        ),
        migrations.AlterModelTable(
            name='distribuidora',
            table='distribuidora',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
        migrations.AlterModelTable(
            name='tipocliente',
            table='tipo_cliente',
        ),
    ]
