# Generated by Django 5.2.4 on 2025-08-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('Mercado libre', 'Mercado libre'), ('Energía Renovable', 'Energía Renovable'), ('Ahorro Energéitco', 'Ahorro Energéitco'), ('Asesoría Legal', 'Asesoría Legal')], max_length=20)),
                ('featured_image', models.ImageField(upload_to='blog/')),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('publication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
