# Generated by Django 5.2.4 on 2025-08-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'managed': False},
        ),
    ]
