# Generated by Django 5.2.4 on 2025-09-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpost_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotoBlog',
            fields=[
                ('id_foto_blog', models.AutoField(primary_key=True, serialize=False)),
                ('url_foto_blog', models.CharField(max_length=255)),
                ('nombre_foto_blog', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'foto_blog',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='blogpost',
            table='blog_post',
        ),
    ]
